#!/bin/bash

# The input file containing the lines you want to check
input_file="$1"

# Check for a provided file
if [[ -z "$input_file" ]]; then
  echo "Please provide an input file."
  exit 1
fi

# The regex pattern
# The (?i) is for case-insensitive matching
# The \s* at the end is for optional trailing whitespace
pattern="^(?i)(ref|refs|reference|references|res|resolve|resolves)[ \t]*:[ \t]*(gh-|\!|[A-Za-z]+-)\d+\s*$"

# Scan the entire file for lines matching the pattern
if grep -Pq "$pattern" "$input_file"; then
  echo "all good"
  exit 0
else
  echo """
  Please add ticket reference to commit message.

  If this commit resolves an issue, add:
  
  res: !123 # For GitHub issues
  res: PROJ-1234 # For other issue tracker IDs

  If this commit is referencing an issue, but does not resolve it, add:

  ref: !123 # For GitHub issues
  ref: PROJ-1234 # For other issue tracker IDs

  See the contributing guidelines of this project for more details.

  Don't have a ticket to reference? You should create one.
  """
  exit 1
fi

